WITH range(1, 1000) AS ids
UNWIND ids AS startId
MATCH (a:Account) WHERE id(a) = startId
MATCH (a)-[:ACCOUTTOLOGINTYPE|ACCOUTTOLEVEL|ACCOUTTOEMAIL|ACCOUTTOTYPE]->(b),
      (b)<-[:ACCOUTTOLOGINTYPE|ACCOUTTOLEVEL|ACCOUTTOEMAIL|ACCOUTTOTYPE]-(c:Account),
      (c)-[:ACCOUTTOLOGINTYPE|ACCOUTTOLEVEL|ACCOUTTOEMAIL|ACCOUTTOTYPE]->(d),
      (d)<-[:ACCOUTTOLOGINTYPE|ACCOUTTOLEVEL|ACCOUTTOEMAIL|ACCOUTTOTYPE]-(e:Account)
WITH DISTINCT e
RETURN COLLECT(e) AS uniqueNeighbors
